/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_human_interface_device         14
#define gattdb_protocol_mode                  16
#define gattdb_report                         18
#define gattdb_report_reference               20
#define gattdb_report_map                     22
#define gattdb_external_report_reference      23
#define gattdb_hid_information                25
#define gattdb_hid_control_point              27
#define gattdb_battery_service                28
#define gattdb_battery_level                  30
#define gattdb_characteristic_presentation_format 31
#define gattdb_device_information             33
#define gattdb_manufacturer_name_string       35
#define gattdb_model_number_string            37
#define gattdb_serial_number_string           39
#define gattdb_hardware_revision_string       41
#define gattdb_firmware_revision_string       43
#define gattdb_software_revision_string       45
#define gattdb_system_id                      47
#define gattdb_pnp_id                         49


#endif // __GATT_DB_H
